### ISSUE TITLE
php72w-pecl-memcached.x86_64 Attempts to install php71w dependencies

### ISSUE THREAD

**Issue by swagopopotamus** [webtatic-rpms/php72w#12]
On CentOS 7 running into the following issue:
I wasn't sure where else to report this issue with the package.

yum install  php72w-pecl-memcached
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: repos.dfw.quadranet.com
 * updates: centos.mirror.ndchost.com
 * webtatic: us-east.repo.webtatic.com
Resolving Dependencies
--> Running transaction check
---> Package php72w-pecl-memcached.x86_64 0:3.0.4-1.w7 will be installed
--> Processing Dependency: php(zend-abi) = 20170718-64 for package: php72w-pecl-memcached-3.0.4-1.w7.x86_64
--> Processing Dependency: php(api) = 20170718-64 for package: php72w-pecl-memcached-3.0.4-1.w7.x86_64
--> Processing Dependency: php-pecl-igbinary(x86-64) for package: php72w-pecl-memcached-3.0.4-1.w7.x86_64
--> Processing Dependency: /usr/bin/pecl for package: php72w-pecl-memcached-3.0.4-1.w7.x86_64
--> Processing Dependency: /usr/bin/pecl for package: php72w-pecl-memcached-3.0.4-1.w7.x86_64
--> Running transaction check
---> Package php71w-pecl-igbinary.x86_64 0:2.0.5-1.w7 will be installed
--> Processing Dependency: php(zend-abi) = 20160303-64 for package: php71w-pecl-igbinary-2.0.5-1.w7.x86_64
--> Processing Dependency: php(api) = 20160303-64 for package: php71w-pecl-igbinary-2.0.5-1.w7.x86_64
---> Package php72w-common.x86_64 0:7.2.16-1.w7 will be installed
---> Package php72w-pear.noarch 1:1.10.4-1.w7 will be installed
--> Processing Dependency: php72w-xml for package: 1:php72w-pear-1.10.4-1.w7.noarch
--> Processing Dependency: php72w-posix for package: 1:php72w-pear-1.10.4-1.w7.noarch
--> Processing Dependency: php72w-cli for package: 1:php72w-pear-1.10.4-1.w7.noarch
--> Running transaction check
---> Package php71w-common.x86_64 0:7.1.27-1.w7 will be installed
---> Package php72w-cli.x86_64 0:7.2.16-1.w7 will be installed
--> Processing Dependency: libargon2.so.0()(64bit) for package: php72w-cli-7.2.16-1.w7.x86_64
---> Package php72w-process.x86_64 0:7.2.16-1.w7 will be installed
---> Package php72w-xml.x86_64 0:7.2.16-1.w7 will be installed
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.24)(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.22)(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.18)(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.13)(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.11)(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Processing Dependency: libxslt.so.1()(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Processing Dependency: libexslt.so.0()(64bit) for package: php72w-xml-7.2.16-1.w7.x86_64
--> Running transaction check
---> Package libargon2.x86_64 0:20161029-2.el7 will be installed
---> Package libxslt.x86_64 0:1.1.28-5.el7 will be installed
--> Processing Conflict: php72w-common-7.2.16-1.w7.x86_64 conflicts php-common < 7.2
--> Finished Dependency Resolution
Error: php72w-common conflicts with php71w-common-7.1.27-1.w7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by andytson** [comment]
I'm unable to recreate, however you may have been able to work around it by installing `php72w-pecl-igbinary` first.

My guess is something was excluding that in your yum configuration, so it tried the next best `php-pecl-igbinary(x86-64)` match that couldn't be satisfied
