### ISSUE TITLE
PHP 7.2.17/18 Release ?

### ISSUE THREAD

**Issue by arfeen** [webtatic-rpms/php72w#13]
Hello

Sorry for the question asking here as issue. Any ETA when do will we have PHP 7.2.17 on the webtactic repo for Centos 7 ?

Thanks

Arfeen

**Comment by stankolubomir** [comment]
Hello,

Andy updated changelog to 7.2.18, but didn't change the Version: https://github.com/webtatic-rpms/php72w/commit/9d4fceb917ef6e0e270bac32918c1cf4721e7c96
So there is only 7.2.17 available in the repository.

We will have to wait for proper 7.2.19 release: https://github.com/webtatic-rpms/php72w/commit/ace6290eb2a8eefe6ef58ca7c442fb7f94df917f

Lubo
