### ISSUE TITLE
php72w no longer available on webtatic 'live' repo?

### ISSUE THREAD

**Issue by MonsieurCellophane** [webtatic-rpms/php72w#14]
As of 2019-07-24 72w is not available from the webtatic repo for CentOS7 (71w is). A version remains in webtatic-archive, but it appears it's broken (or @least, I was unable to install successfully). 

Absent, however, is a comment on the reason why, or on when/if it will be restored.

**Comment by andytson** [comment]
there appears no trouble installing php72w packages from the stable repository (webtatic rather than webtatic-archive) on CentOS 7, so I expect the problem is on your machine.
