### ISSUE TITLE
php72w-pecl-imagick needs libMagickCore.so.5 which isn't in latest ImageMagick update

### ISSUE THREAD

**Issue by BenArgyle** [webtatic-rpms/php72w#16]
I'm running RHEL7, and just doing the big update from 7.7 to 7.8 and one of the updates is to ImageMagick (6.7.8.9 to 6.9.10.68).  This seems to get rid of libMagickCore.so.5, which php72w-pecl-imagick doesn't like:

[...]
---> Package ImageMagick.x86_64 0:6.7.8.9-18.el7 will be updated
--> Processing Dependency: libMagickCore.so.5()(64bit) for package: php72w-pecl-imagick-3.4.3-1.2.w7.x86_64
--> Processing Dependency: libMagickWand.so.5()(64bit) for package: php72w-pecl-imagick-3.4.3-1.2.w7.x86_64
---> Package ImageMagick.x86_64 0:6.9.10.68-3.el7 will be an update
--> Finished Dependency Resolution
Error: Package: php72w-pecl-imagick-3.4.3-1.2.w7.x86_64 (@webtatic)
           Requires: libMagickWand.so.5()(64bit)
           Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@rhel-7-server-rpms)
               libMagickWand.so.5()(64bit)
           Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (rhel-7-server-rpms)
               Not found
           Available: ImageMagick-6.7.8.9-10.el7.x86_64 (rhel-7-server-rpms)
               libMagickWand.so.5()(64bit)
           Available: ImageMagick-6.7.8.9-12.el7_2.x86_64 (rhel-7-server-rpms)
               libMagickWand.so.5()(64bit)
           Available: ImageMagick-6.7.8.9-13.el7_2.x86_64 (rhel-7-server-rpms)
               libMagickWand.so.5()(64bit)
           Available: ImageMagick-6.7.8.9-15.el7_2.x86_64 (rhel-7-server-rpms)
               libMagickWand.so.5()(64bit)
           Available: ImageMagick-6.7.8.9-16.el7_6.x86_64 (rhel-7-server-rpms)
               libMagickWand.so.5()(64bit)
[...]

Thoughts?

**Comment by BenArgyle** [comment]
This issue also affects php56w-pecl-imagick.

**Comment by andytson** [comment]
php72w-pecl-imagick has been updated. php versions before that are end of life, so won't be receiving fixes.
