### ISSUE TITLE
curl: (60) Peer's Certificate has expired.

### ISSUE THREAD

**Issue by luisnuxx** [webtatic-rpms/php72w#3]
Retrieving https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
curl: (60) Peer's Certificate has expired.

**Comment by andytson** [comment]
I double checked all the servers and their certificates still appear in date

**Comment by Diabolush** [comment]
I am also getting the Peer Certificate has expired error and if I go to the URL, I get an invalid certificate on my browser.

**Comment by Diabolush** [comment]
Actually, the certificate expired today (March 1st).

Common Name (CN)	webtatic.com
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	<Not Part Of Certificate>
Common Name (CN)	Let's Encrypt Authority X3
Organization (O)	Let's Encrypt
Organizational Unit (OU)	<Not Part Of Certificate>
Issued On	Saturday, December 1, 2018 at 8:13:11 AM
Expires On	Friday, March 1, 2019 at 8:13:11 AM

**Comment by cphalpin** [comment]
Yep, I'm seeing the same thing but if I check it with a browser on my local machine it's apparently good till May.

**Comment by andytson** [comment]
Sorry there are multiple servers, and different locations resolve to different servers by default.

The issue on the server that this renewal failed to automatically happen is resolved now

**Comment by Diabolush** [comment]
Working now.  Thanks!
