### ISSUE TITLE
Sodium disabled ?

### ISSUE THREAD

**Issue by FolkenFR** [webtatic-rpms/php72w#4]
Hello,
Can you explain why sodium was disabled ?
Thank U

**Comment by andytson** [comment]
Sodium (the updated version of libsodium php extension) increased its libsodium (the C library) dependency version requirement beyond the version supplied by EPEL 7 at the time to 1.0.15

It looks like now EPEL has updated libsodium (the C library) to 1.0.16, and sodium has reduced it's libsodium (the C library) version requirements to 1.0.9, so I will enable it for the next build.

Until then libsodium (php extension) is available under php72w-pecl-libsodium, but I will get the updated sodium extension sorted in the next few days.

**Comment by FolkenFR** [comment]
Thank U for your answer. I will wait your next release.

**Comment by andytson** [comment]
@FolkenFR it's in the testing repository now, can get it by adding --enablerepo=webtatic-testing whilst installing php72w-sodium e.g.
```
yum install --enablerepo=webtatic-testing php72w-sodium
```

**Comment by FolkenFR** [comment]
Thank you for your speed. I'm going to test this week or next week.

**Comment by FolkenFR** [comment]
It worked! Thank you. Just for information, I had to install the apache module
